#!/bin/bash

declare -a myarr
declare -a speedarr
echo "Enter urls:"

read -a myarr

speed=0

for element in ${myarr[@]}
do
  speed=$(ping -c 1 $element | grep "round-trip" | cut -f5 -d "/")
  speedarr+=( "$element $speed")
done
echo "output"
for element in ${speedarr[@]}
do
  echo $element
done
