#!/bin/bash
logedin=false
password="Pizza"
while [ $logedin == false ]; do
echo "Enter password:"
read Attempt
if [[ $Attempt == $password ]]; then
echo "yay"
logedin=true
fi
done

first=$1
second=$2
point=$(($first -1))
sum=0
echo "first: $1 , second: $2"
until [ $point == $second ]; do
 point=$(($point + 1))
 #echo $point
 sum=$(($sum + $point**2))
done
echo $sum
